VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ParamType"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_HelpID = 1
Attribute VB_Description = "A simple parameter containing Name, Value which is used for the cookie and parameter collections."
Option Explicit

Public Name As String
Public Value As String
